services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: apifactory
      POSTGRES_USER: apifactory
      POSTGRES_PASSWORD: apifactory
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U apifactory -d apifactory"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine

  api:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./:/app   # <— repo completo dentro del contenedor

  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
      - db
    command: ["bash","-lc","celery -A app.celery_app.celery worker --loglevel=INFO"]
    volumes:
      - ./:/app

volumes:
  pgdata:
